### ISSUE TITLE
Using variables for icons and search bar

### ISSUE THREAD

**Issue by lakejason0** [lakejason0/mediawiki-skins-Lakeus#12]
As we are going to make Theme Designer, the color must be all passed by CSS variables, and we also need a widely supported way to invert the colors of the icons, sth sth.

**Comment by winstonsung** [comment]
Done in:
* #10
( c3b7de96a369e7ce10028c2a73bbd4fe416cee1d )

**Comment by winstonsung** [comment]
* 2b6eaa92e87872176bfb181fc763b33fcbdb025c
