### ISSUE TITLE
Help using Theme Designer for Lakeus skin for MediaWiki?

### ISSUE THREAD

**Issue by michaelbeijer** [lakejason0/mediawiki-skins-Lakeus#15]
Hi there!

I really like your MediaWiki skin, but can't figure out how to make the stuff I change with your Theme Designer actually stay that way on my wiki: https://termhotel.com/ 

I copied the css to my clipboard (with Copy theme), but then what?

I tried clicking Paste current settings, but nothing seems to happen...

On this page: https://www.mediawiki.org/wiki/Skin:Lakeus
You said: "_**Below is the default setting of CSS variables; modify these settings and put the result into your Lakeus.css:**_"

But I can't find the file **Lakeus.css** anywhere.

Best wishes,

Michael

**Comment by lakejason0** [comment]
Here's the thing:
So, MediaWiki will load the page `MediaWiki:Lakeus.css` when you are using Lakeus; if you are an admin (of course as you said?) you can copy the code generated in the clipboard to that page to apply the theme globally. If you are only one of the users, you can try to apply to your User CSS, which would be `Special:MyPage/Lakeus.css`.
And... unfortunately Theme Designer is not quite stable and as I totally forget my coding for I had to prepare for my exam, the designer might need a refactor. Hope you enjoy the current version tho (imo it's crappy),
I will update the documentation on MediaWiki.org.
