### ISSUE TITLE
Highlight selected variant

### ISSUE THREAD

**Issue by TripleCamera** [lakejason0/mediawiki-skins-Lakeus#17]
In Lakeus, the selected variant looks same with other variants. Please highlight it so that users can know which variant they are using. 
![issue1](https://user-images.githubusercontent.com/66164427/175057203-bcc4cdfd-6d39-4702-b25a-67e9d34c3525.PNG)

P.S. They are (slightly) different in Timeless. 
![issue2](https://user-images.githubusercontent.com/66164427/175057193-e10347f1-ba42-4e3e-861f-01cb84a88001.PNG)

**Comment by lakejason0** [comment]
acknowledged, will fix later

**Comment by winstonsung** [comment]
( v1.1.12 , ca7d3d48597c10c837676502cc21557b05d7a308 )
