### ISSUE TITLE
#39 | Convert to Codex & FDS breakpoints

### ISSUE THREAD

**Issue by winstonsung** [lakejason0/mediawiki-skins-Lakeus#39]
* https://doc.wikimedia.org/codex/latest/design-tokens/breakpoint.html
* https://fandomdesignsystem.com/?path=/docs/base-breakpoints--docs

**Comment by winstonsung** [comment]
* `0px` FDS `$wds-breakpoint-small`
* `320px` Codex `min-width-breakpoint-mobile`
* `640px` Codex `min-width-breakpoint-tablet`
* `768px` FDS `$wds-breakpoint-medium`
* `1024px` FDS `$wds-breakpoint-large`
* `1120px` Codex `min-width-breakpoint-desktop`
* `1280px` FDS `$wds-breakpoint-xlarge`
* `1500px` FDS `$wds-breakpoint-xxlarge`
* `1680px` Codex `min-width-breakpoint-desktop-wide`

**Comment by lakejason0** [comment]
#40 修的不是很好。本质上我写 `min-width` 是因为内容区宽度在断点变化的时候，会从窄瞬间变宽，而后变窄。

**Comment by winstonsung** [comment]
> #40 修的不是很好。本质上我写 `min-width` 是因为内容区宽度在断点变化的时候，会从窄瞬间变宽，而后变窄。

先revert了。

**Comment by winstonsung** [comment]
(no longer needed)
