### ISSUE TITLE
#48 | Dropdowns could get too long esp. for languages

### ISSUE THREAD

**Issue by lakejason0** [lakejason0/mediawiki-skins-Lakeus#48]
**Steps to replicate the issue** (include links if applicable):

* Go to [MediaWiki Skins Lab Tools demo](https://skins-demo.wmflabs.org//wiki/MediaWiki?useformat=desktop&uselang=en&useskin=lakeus)
* Click "In other languages"
* Seeing a overly long dropdown menu

**What happens?**:
The dropdown menu is toooooooooooooooooooooooo long to use

**What should have happened instead?**:
Maybe scrollable?

**Software version** (on `Special:Version` page):

* MediaWiki: 1.42.0-alpha
* Lakeus skin: 1.2.0

**Other information** (browser name/version, screenshots, etc.):

**Comment by lakejason0** [comment]
need test on adding a simple `min-height: 60vh`

**Comment by winstonsung** [comment]
Fixed in https://github.com/lakejason0/mediawiki-skins-Lakeus/commit/4d20d7e7353dac3120d80fe4ed3ecf74391c57ce
